@startuml
package "shared.domain.model" {
    class Currency {
        - #code: CurrencyCode
        + code: CurrencyCode
        + formatAmount(amount: number, locale: string): string
        + toString(): string
    }

    class Money {
        - #amount: number
        - #currency: Currency
        + amount: number
        + currency: Currency
        + format(locale: string): string
        + toString(): string
        + add(other: Money): Money
        + multiply(factor: number): Money
    }

    class DateTime {
        - #date: Date
        + value: Date
        + format(locale: string): string
        + toString(): string
    }
}

package "crm.domain.model" {
    class Customer {
        - #id: string
        - #name: string
        - #lastOrderPrice: Money | null
        + id: string
        + name: string
        + lastOrderPrice: Money | null
    }
}

package "sales.domain.model" {

    class ProductId {
        - #id: string
        + id: string
    }

    class SalesOrderItem {
        - #orderId: string
        - #itemId: string
        - #productId: ProductId
        - #quantity: number
        - #unitPrice: Money
        + orderId: string
        + itemId: string
        + productId: ProductId
        + quantity: number
        + unitPrice: Money
        + calculateItemTotal(): Money
    }

    class SalesOrder {
        - #customerId: string
        - #id: string
        - #items: SalesOrderItem[]
        - #orderedAt: DateTime
        - #currency: Currency
        - #state: SalesOrderState
        + customerId: string
        + id: string
        + items: ReadonlyArray<SalesOrderItem>
        + orderedAt: DateTime
        + currency: Currency
        + state: SalesOrderState
        + addItem(productId: ProductId, quantity: number, unitPriceAmount: number): void
        + calculateTotalAmount(): Money
        + getFormattedOrderedAt(): string
        + confirm(): void
        + cancel(): void
        + ship(): void
    }
}

Customer "1" o-- "0..*" SalesOrder
SalesOrder "1" *-- "1..*" SalesOrderItem
SalesOrderItem "1" -- "1" ProductId
SalesOrderItem "1" -- "1" Money
Money "1" -- "1" Currency
SalesOrder "1" -- "1" DateTime
@enduml